### PR TITLE
feature: Implement `billing-integrations stripe` CLI

### PR DESCRIPTION
**Pull request by jshearer**
* For the moment, invoices are created as drafts and have to be approved and sent/paid manually. A draft invoice can be edited, but not sent or paid.
* One of the next steps is to display invoice PDFs or links to Stripe's hosted invoice page in the dashboard. Neither of these are available for draft invoices, so only invoices that are manually approved will show the PDF/hosted link.
* These invoices are being entered as `collection_method: SendInvoice`, which _requires_ that the associated customer has an email that can receive the invoice. Customers that have already entered payment details will have this email set, but rather than skip all of the customers that haven't gone through that process, I decided to pick the email address of an `admin` user on their tenant. This is only the default, and can be changed once created later.

```
Publish bills from the control-plane database as Stripe invoices

USAGE:
    billing-integrations stripe [OPTIONS] --connection-string <CONNECTION_STRING> --stripe-api-key <STRIPE_API_KEY> --month <MONTH>

OPTIONS:
        --all-tenants
            Generate invoices for all tenants that have bills in the provided month

        --connection-string <CONNECTION_STRING>
            Control-plane DB connection string

        --fail-fast
            Stop execution after first failure

    -h, --help
            Print help information

        --month <MONTH>
            The month to generate invoices for, in format "YYYY-MM-DD"

        --recreate-finalized
            Whether to delete and recreate finalized invoices

        --stripe-api-key <STRIPE_API_KEY>
            Stripe API key

        --tenants <TENANTS>
            Comma-separated list of tenants to publish invoices for
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/1180)

### CODE REVIEW

**Review by jgraettinger — COMMENTED** [review]
IIRC we'd discussed this living in another crate that's not part of the workspace, that can have its own Cargo.toml and be invoked via `cargo run`. Is there a reason why `flowctl` is more appropriate?

**Comment by jgraettinger** [comment]
I see you're also using the PostgREST API rather than `sqlx` for access. This presumes the capabilities of the current `estuary_support/` role, but we actually want to remove that role. When creating reports for multiple tenants this is basically going to _require_ direct DB access.

**Comment by jshearer** [comment]
wait, another crate that's not even in the _workspace_? Do you want me to make a new repo? Or where would it go?

**Comment by jshearer** [comment]
Moved into separate crate, and updated to use sqlx 👍

**Review by jgraettinger — APPROVED** [review]
LGTM!

Not knowledgeable about Stripe's API, but for things i do understand this is great. Thanks for re-working it

**Pull request merged**
