### PR TITLE
inference::Exists & build / typescript generation

### PR DESCRIPTION
**Pull request by jgraettinger**
Bundling a one-off commit with a couple of related build / typescript generation commits.

Recommend reviewing this one commit-by-commit

---
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/97)

### CODE REVIEW

**Review by psFried — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 13 of 13 files at r2, 33 of 33 files at r3.
> *[Reviewable](https://reviewable.io/reviews/estuary/flow/97)* status: all files reviewed, 1 unresolved discussion (waiting on @jgraettinger)

___
*[crates/build/src/lib.rs, line 105 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTGX_Bc7HYs0lrEIeoj:-MTGX_Bc7HYs0lrEIeok:b-6n0urn) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/lib.rs#L105)):*
> ```XML
> 
> pub fn generate_typescript_package(tables: &tables::All, dir: &Path) -> Result<(), anyhow::Error> {
>     assert!(dir.is_absolute() && dir.is_dir());
> ```

nit: Why does this need to be absolute? Maybe worth just adding a doc comment on this function, anyway. Actually, all three of these functions could maybe use some doc comments to clarify the expectations of `dir` before the function is called and the state it'll be left in afterward.
___
*[crates/build/src/web_fetcher.rs, line 32 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTGj1Fi0D7tx6ahJTnD:-MTGj1Fi0D7tx6ahJTnE:bfx97yi) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/web_fetcher.rs#L32)):*
> ```XML
>             }
>             "http" | "https" => {
>                 let request = hyper::Request::get(resource.as_str())
> ```

I think this is fine for now, but I'll leave some thoughts here for possible future improvements.
It would be good to follow (at least some) redirects. And I'm not sure if `hyper_tls` uses the system's CA certificates, but I don't think it does, and it would be an important feature. I'm thinking it might make sense to switch to the `reqwest` library, since it makes that kind of thing a little easier and also builds on more platforms.
___
*[crates/build/src/nodejs/generators.rs, line 178 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTGxaQKBwReNiRnQby0:-MTGxaQKBwReNiRnQby1:bovw4ia) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/nodejs/generators.rs#L178)):*
> ```XML
> // Generated from derivation {scope}.
> // Required to be implemented by {module}.
> export interface {name} {{
> ```

These comments will be really helpful. It seems like a good idea to render them using the doc comment syntax `/** ... */`. I'd expect VSCode would show doc comments in the little info popups for you, and it would be nice to enable the use of tools like tsdoc as well. This could just come in a later, PR, though, since it would just be a small quality of life improvement.
___
*[crates/build/src/nodejs/typescript/ast.rs, line 4 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTH0u-s1YmhE87LdfA7:-MTH0u-s1YmhE87LdfA8:bwdf60l) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/nodejs/typescript/ast.rs#L4)):*
> ```XML
> 
> #[derive(Debug, Clone, PartialEq)]
> pub enum AST {
> ```

I just got wondering if perhaps the [swc project](https://github.com/swc-project/swc) might expose some useful stuff that we could use. Seems like it might, but it's totally understandable if you reckon it's not worth investing the time digging into it at this point.
___
*[crates/doc/src/inference.rs, line 983 at r1](https://reviewable.io/reviews/estuary/flow/97#-MTGV8W8-Hv9BsKWId-z:-MTGV8W93dSqQlQ7xFt8:bbq0nqj) ([raw file](https://github.com/estuary/flow/blob/97adc02bf5061da96b01e7ee4d213fc621d8fedd/crates/doc/src/inference.rs#L983)):*
> ```XML
> /// Exists captures an existence constraint of an Shape location.
> #[derive(Debug, Copy, Clone, Eq, PartialEq)]
> pub enum Exists {
> ```

This is great. I like that it also provides a little safety so we don't accidentally end up using a pointer with a `-` in situations where it doesn't make sense.

**Review by jgraettinger — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/estuary/flow/97#-:-MTH7q6nEYRekKbvZjBT:b-ucfknh)* status: all files reviewed, 1 unresolved discussion (waiting on @psFried)

___
*[crates/build/src/lib.rs, line 105 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTGX_Bc7HYs0lrEIeoj:-MTH6_Yd27FL28d-xHEB:b-q7f4uc) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/lib.rs#L105)):*
<details><summary><i>Previously, psFried (Phil Fried) wrote…</i></summary><blockquote>

nit: Why does this need to be absolute? Maybe worth just adding a doc comment on this function, anyway. Actually, all three of these functions could maybe use some doc comments to clarify the expectations of `dir` before the function is called and the state it'll be left in afterward.
</blockquote></details>

Yep, I'm going to add this as a future fix-up commit if that's okay.
___
*[crates/build/src/web_fetcher.rs, line 32 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTGj1Fi0D7tx6ahJTnD:-MTH6fIxDBFAdnmCwLCV:b6axb2n) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/web_fetcher.rs#L32)):*
<details><summary><i>Previously, psFried (Phil Fried) wrote…</i></summary><blockquote>

I think this is fine for now, but I'll leave some thoughts here for possible future improvements.
It would be good to follow (at least some) redirects. And I'm not sure if `hyper_tls` uses the system's CA certificates, but I don't think it does, and it would be an important feature. I'm thinking it might make sense to switch to the `reqwest` library, since it makes that kind of thing a little easier and also builds on more platforms.
</blockquote></details>

Hah we had been using reqwest in `catalog`, and I actually ripped it out because the only value over hyper was redirect following. `hyper_tls` does use the system TLS library ; i was pretty sure it's using the system CA certs as well.

I've actually been thinking that catalog building should be a bridged library , that flowctl should be a Go process, and that the actual responsibility for fetching resources should live within Go. Let's talk about that outside of here.
___
*[crates/build/src/nodejs/typescript/ast.rs, line 4 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTH0u-s1YmhE87LdfA7:-MTH7Smx8pgBY1cUal5b:bp69zfw) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/nodejs/typescript/ast.rs#L4)):*
<details><summary><i>Previously, psFried (Phil Fried) wrote…</i></summary><blockquote>

I just got wondering if perhaps the [swc project](https://github.com/swc-project/swc) might expose some useful stuff that we could use. Seems like it might, but it's totally understandable if you reckon it's not worth investing the time digging into it at this point.
</blockquote></details>

? i'm not familiar with it / don't know what it would bring

**Review by jgraettinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/estuary/flow/97)* status: all files reviewed, 1 unresolved discussion (waiting on @psFried)

___
*[crates/build/src/lib.rs, line 105 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTGX_Bc7HYs0lrEIeoj:-MTH7wFn9ZzLtP83dIVG:b-jlu0xg) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/lib.rs#L105)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Yep, I'm going to add this as a future fix-up commit if that's okay.
</blockquote></details>

Oh the reason it needs to be absolute is we test resource URLs against it to determine if a given typescript module resource is external or relative.

**Review by jgraettinger — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/estuary/flow/97)* status: all files reviewed, 1 unresolved discussion (waiting on @psFried)

___
*[crates/build/src/nodejs/typescript/ast.rs, line 4 at r2](https://reviewable.io/reviews/estuary/flow/97#-MTH0u-s1YmhE87LdfA7:-MTH8efq6Q-T9JW0j9dv:bkiybke) ([raw file](https://github.com/estuary/flow/blob/bf59d2092201972b7448848362a3dd26fa56a8f2/crates/build/src/nodejs/typescript/ast.rs#L4)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

? i'm not familiar with it / don't know what it would bring
</blockquote></details>

oh i see it's a deno related projection doing "typescript compilation". This seems like pretty dangerous ground -- the whole point of typescript is strong static check guarantees; I don't see how this could possibly be replicating the level of checks done by `tsc`, and am guessing it's primary goal is just compatibility with the syntax.

**Pull request merged**
