### PR TITLE
validation: more intuitive error message for expected pub

### PR DESCRIPTION
**Pull request by mdibaiee**
**Description:**

- the original error is too technical for most users to understand what it means

**Workflow steps:**

(How does one use this feature, and how has it changed)

**Documentation links affected:**

(list any [documentation links](https://docs.google.com/document/d/1SRC9VS9zyCzWl3n4HXHbc4wPB1eLxJHkA2rtu9ZNokM/edit?usp=sharing) that you created, or existing ones that you've identified as needing updates, along with a brief description)

**Notes for reviewers:**

(anything that might help someone review this PR)

- - -
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/1498)

### CODE REVIEW

**Review by psFried — CHANGES_REQUESTED** [review]
Thanks for bringing this up. I'd like to pile on and suggest a further improvment:

~this usually means~ another publication has modified ~the resources included in this publication~ this spec; to avoid conflicts, please refresh the resources and try again

I feel like "refresh the resources" is also rather vague, though I don't have a ready suggestion. If the user was publishing via flowctl, then they need to run `pull-specs` with `--overwrite`, and then make their edits again and re-publish. If they were publishing via the UI, then they need to cancel their current edit and start over.

The "refresh" terminology might be a bit misleading in the UI, because I _think_ (not sure, looking to @travjenkins or @kiahna-tucker to confirm) that if a user is on the edit page and they re-load the page, then it will preserve their previous draft so they would just get the same error again. My understanding is that in the UI they'd need to cancel their edit entirely and start over from the beginning. Technically, they might be able to just re-fresh the bindings if the error was for a collection spec when editing a capture, but that feels like too much nuance to try to communicate in an error message.

**Review by dyaffe — CHANGES_REQUESTED** [review]
I would probably switch to this since the common path is that your changes were already made:

expected publication ID {expect_id} was not matched (it's actually {actual_id}): this usually means your changes have already been made; to avoid conflicts, please refresh the resources and confirm.

**Comment by mdibaiee** [comment]
> another publication has modified this spec; to avoid conflicts, please refresh the resources and try again

I think "spec" is still a very technical word and not quite as obvious what it means for the "spec" to have been modified. I'm trying to think through the eyes of a user who has just landed on our dashboard for the first time and has created a capture and a materialization and went to update it for the first time and got this error. We do use the word in the UI though, we call the editor "Advanced Specification Editor" and in the details page of tasks and collections we have "SPEC" tab, so perhaps I'm being pessimistic and it is a familiar word for users.

> I feel like "refresh the resources" is also rather vague

I agree, it irks me as well... given that users need to start over in the UI and they need to fetch the remote spec again before continuing in flowctl, I guess we could say "please try the operation again on a fresh copy of specifications" or something of the sort?

**Comment by kiahna-tucker** [comment]
>  if a user is on the edit page and they re-load the page, then it will preserve their previous draft so they would just get the same error again. My understanding is that in the UI they'd need to cancel their edit entirely and start over from the beginning.

Yes Phil, that is correct.

**Comment by mdibaiee** [comment]
> expected publication ID {expect_id} was not matched (it's actually {actual_id}): this usually means your changes have already been made; to avoid conflicts, please refresh the resources and confirm.

@dyaffe this case of a change already having been made, to me is more of a bug in the UI that needs to be fixed to be honest. I've hit this issue a few times, where I hit Save, the publication is published but I'm not redirected / the page is not refreshed as usual, so I end up trying to save again only to hit this error. The error would be misleading in other scenarios though (when multiple tabs edit the resource, etc.)

**Comment by dyaffe** [comment]
@mdibaiee everyone says that and we attempted to fix this but 100% of the time that a user has gotten this error message so far, it has been a double click in the UI.

**Comment by mdibaiee** [comment]
How about this? I would personally prefer if the ending was a bit more clear (a fresh copy of the spec might not be as clear), so please suggest if you have a better idea 🤔 

> expected publication ID {expect_id} was not matched (it's actually {actual_id}): your changes have already been published or another publication has modified this spec; please try again with a fresh copy of the spec.

**Review by dyaffe — APPROVED** [review]
I'm not in love with the phrasing "with a fresh copy of the spec.", but don't have anything better.

**Pull request merged**
