### PR TITLE
Docs: update derivation concepts and samples

### PR DESCRIPTION
**Pull request by oliviamiannone**
**Description:**

Updates docs per https://github.com/estuary/flow/pull/460. Reflects changes to derivation spec and ts generation. (The broader updates to flowctl will be covered by a separate PR soon).

Includes updates to all the acmeBank catalog examples in the derivations concept docs, and re-generated typescript files.

**Notes for reviewers:**

I may be jumping the gun on submitting this -- perhaps I should have waited until the `examples` tenant is configured so I can test the whole acmeBank catalog. But I've been sitting on the actual docs themselves for a little while now and I wanted to get eyes on them sooner rather than later.

---
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/473)

### CODE REVIEW

**Review by jgraettinger — CHANGES_REQUESTED** [review]
Thanks for this! looks good in broad strokes but some comments below

> Reviewed 13 of 13 files at r1, 1 of 4 files at r2, 1 of 2 files at r3, 1 of 5 files at r4, 25 of 25 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/estuary/flow/473#-:-N2qZ4n20LY0HsoGwUC_:be74h39)* status: all files reviewed, 11 unresolved discussions (waiting on @oliviamiannone)

___
*[`site/docs/concepts/derivations.md` line 293 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qMHN62dZhXJAknjO1:-N2qMHN62dZhXJAknjO2:b-ngdaeu) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/derivations.md#L293)):*
> ```Markdown
> through its extracted [shuffle key](#shuffles).
> 
> For example, when shuffling `acmeBank/transfers` on `[/sender]`,
> ```

Proposed update to make this a bit more concrete:

For example, when shuffling `acmeBank/transfers` on `[/sender]` or `[/recipient]`
then each account ("alice", "bob", or "carol")
is allocated its own register.
You might use that register to track a current account balance
given the received inflows and sent outflows of each account.

If you instead shuffle on `[/sender, /recipient]` then each
_pair_ of accounts ("alice -> bob", "alice -> carol", "bob -> carol")
is allocated a register.

Transformations of a derivation may have different shuffle keys,
but the number of key components and their JSON types must agree.
Two transformations could map on `[/sender]` and `[/recipient]`,
but not `[/sender]` and `[/recipient, /sender]`.
___
*[`site/docs/concepts/derivations.md` line 323 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qOPq7-9jNh5GnrRHF:-N2qOPq7-9jNh5GnrRHG:b-pm9tl7) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/derivations.md#L323)):*
> ```Markdown
> ## Lambdas
> 
> Lambdas are user-defined functions that are invoked by a derivation.
> ```

Suggest replacing with:

Lambdas are user-defined functions that accept documents as arguments
and return transformed documents in response.
Lambdas can be used to update registers, publish documents into a derived collection,
or (soon) compute a non-trivial shuffle key of a document.

Flow supports TypeScript lambdas, which you define in an accompanying TypeScript module
and reference in [a derivation's`typescript` stanzas](#specification).
See [TypeScript generation](./flowctl.md#typescript-code-generation) for more details on how to get started.
TypeScript lambdas are "serverless": Flow manages the execution and scaling of your Lamba on your behalf.

Alternatively Flow also supports _remote_ lambdas which invoke an HTTP endpoint you provide,
such as an AWS Lambda or Google Cloud Run function.

In terms of the map / reduce functional programming paradigm,
Flow lambdas are "mappers"
which map documents into new user-defined shapes, 
while [reductions](./schemas.md#reductions) are implemented by Flow
using the reduction annotations of your collection schemas.


/ Somewhere else where we briefly document remote lambdas. We probably don't want to get too into this yet / mark it as a stub? :

A remote Lambda is one which you implement and host yourself as a web-accessible endpoint, typically via a service like AWS Lambda or Google Cloud Run. Flow will invoke your remote Lambda as needed, POST-ing JSON documents to process and expecting JSON documents in the response.
___
*[`site/docs/concepts/derivations.md` line 643 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qWNoXAUacob62Q1r0:-N2qWNoXAUacob62Q1r1:btwkz2l) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/derivations.md#L643)):*
> ```Markdown
> 
> </TabItem>
> <TabItem value="catalog.flow.ts" default>
> ```

nit: should be called `first-send.flow.ts` since that's what's in the catalog.

Maybe used `my-module.ts` or something for generality?
___
*[`site/docs/concepts/flowctl.md` line 72 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qUEZL8K7N0xMtjjBg:-N2qUEZMCIGICDCR9EIX:b3k2j7h) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/flowctl.md#L72)):*
> ```Markdown
> ### TypeScript code generation
> 
> TypeScript files are used in two major ways in your Flow catalog:
> ```

I'm not sure what "two major ways" means?

For the user, TypeScript modules are used to define user lambdas. 

FYI publish, update, and (future) shuffle lambdas are all specific to derivations today, but there are potential future use cases around captures, and I do expect lambdas will have increasingly relevance for other task types. :shrug: not sure what that means for docs today.
___
*[`site/docs/concepts/bank/.eslintrc.js` line 1 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qWlGRBYc-pzSRhpeH:-N2qWlGRBYc-pzSRhpeI:b-v1ke8o) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/.eslintrc.js#L1)):*
> ```JavaScript
> module.exports = {
> ```

You don't need to commit this file.
___
*[`site/docs/concepts/bank/.prettierrc.js` line 1 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qWs2o1cnLwMIQLnDJ:-N2qWs2o1cnLwMIQLnDK:bagdxja) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/.prettierrc.js#L1)):*
> ```JavaScript
> module.exports = {
> ```

You don't need to commit this file
___
*[`site/docs/concepts/bank/first-send.flow.ts` line 15 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qX1Vd3i_OBvr7hw2y:-N2qX1Vd3i_OBvr7hw2z:b-jycbx7) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/first-send.flow.ts#L15)):*
> ```XML
>         previous: Register,
>     ): Document[] {
>          // If the register was previously false, than this is the first
> ```

nit: extra space (format?)
___
*[`site/docs/concepts/bank/last-large-send.flow.yaml` line 11 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXAnF504SfkspiC6s:-N2qXAnF504SfkspiC6t:b-6lekd1) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/last-large-send.flow.yaml#L11)):*
> ```YAML
>     derivation:
>       typescript:
>         module: last-large-send.flow.ts
> ```

optional nit: the `*.flow.ts` could just be `*.ts`.

`flow.ts` is vestigial from when we were looking for a ts module that lived alongside the flow catalog, also ending in `*.flow.yaml`, but isn't needed anymore and isn't a convention we want to push.

:shrug:  though.
___
*[`site/docs/concepts/bank/package.json` line 1 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXSK00YFl8bXtqa_4:-N2qXSK00YFl8bXtqa_5:bagdxja) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/package.json#L1)):*
> ```JSON
> {
> ```

You don't need to commit this file
___
*[`site/docs/concepts/bank/tsconfig.json` line 2 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXTVQ84zBLSZ_RWBg:-N2qXTVQ84zBLSZ_RWBh:bagdxja) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/tsconfig.json#L2)):*
> ```jsonc
> {
> 	"compilerOptions": {
> ```

You don't need to commit this file
___
*[`site/docs/concepts/bank/flow_generated/tsconfig-files.json` line 3 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXU6LCGlPxQbMzNxT:-N2qXU6LCGlPxQbMzNxU:balo125) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/flow_generated/tsconfig-files.json#L3)):*
> ```JSON
> {
>   "files": [
>     "../flow_generated/flow/main.ts",
> ```

You don't need to commit this file, or anything else under `flow_generated`.

I'll suggest adding a `.gitignore` file with `flow_generated` and other files which should be skipped.

**Review by oliviamiannone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/estuary/flow/473)* status: 7 of 30 files reviewed, 9 unresolved discussions (waiting on @jgraettinger)

___
*[`site/docs/concepts/derivations.md` line 293 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qMHN62dZhXJAknjO1:-N2s25YS8ZxBJ5j_luJI:b-896fix) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/derivations.md#L293)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Proposed update to make this a bit more concrete:

For example, when shuffling `acmeBank/transfers` on `[/sender]` or `[/recipient]`
then each account ("alice", "bob", or "carol")
is allocated its own register.
You might use that register to track a current account balance
given the received inflows and sent outflows of each account.

If you instead shuffle on `[/sender, /recipient]` then each
_pair_ of accounts ("alice -> bob", "alice -> carol", "bob -> carol")
is allocated a register.

Transformations of a derivation may have different shuffle keys,
but the number of key components and their JSON types must agree.
Two transformations could map on `[/sender]` and `[/recipient]`,
but not `[/sender]` and `[/recipient, /sender]`.

</blockquote></details>

Done.
___
*[`site/docs/concepts/derivations.md` line 323 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qOPq7-9jNh5GnrRHF:-N2s28RS4QXwxw67KXbY:bluoevd) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/derivations.md#L323)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Suggest replacing with:

Lambdas are user-defined functions that accept documents as arguments
and return transformed documents in response.
Lambdas can be used to update registers, publish documents into a derived collection,
or (soon) compute a non-trivial shuffle key of a document.

Flow supports TypeScript lambdas, which you define in an accompanying TypeScript module
and reference in [a derivation's`typescript` stanzas](#specification).
See [TypeScript generation](./flowctl.md#typescript-code-generation) for more details on how to get started.
TypeScript lambdas are "serverless": Flow manages the execution and scaling of your Lamba on your behalf.

Alternatively Flow also supports _remote_ lambdas which invoke an HTTP endpoint you provide,
such as an AWS Lambda or Google Cloud Run function.

In terms of the map / reduce functional programming paradigm,
Flow lambdas are "mappers"
which map documents into new user-defined shapes, 
while [reductions](./schemas.md#reductions) are implemented by Flow
using the reduction annotations of your collection schemas.


/ Somewhere else where we briefly document remote lambdas. We probably don't want to get too into this yet / mark it as a stub? :

A remote Lambda is one which you implement and host yourself as a web-accessible endpoint, typically via a service like AWS Lambda or Google Cloud Run. Flow will invoke your remote Lambda as needed, POST-ing JSON documents to process and expecting JSON documents in the response.

</blockquote></details>

Done, with slight tweaks.
___
*[`site/docs/concepts/flowctl.md` line 72 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qUEZL8K7N0xMtjjBg:-N2s-5fjCo61Sy4uNkuq:b5drsw8) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/flowctl.md#L72)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

I'm not sure what "two major ways" means?

For the user, TypeScript modules are used to define user lambdas. 

FYI publish, update, and (future) shuffle lambdas are all specific to derivations today, but there are potential future use cases around captures, and I do expect lambdas will have increasingly relevance for other task types. :shrug: not sure what that means for docs today.
</blockquote></details>

Just referencing the difference between the generated TS files in flow_generated which the user never needs to touch, vs the ones that they have to manually configure to write lambdas. Seemed like a worthwhile distinction for someone poking around in a Flow catalog for the first time. Or at least, it was for my conceptual understanding. I do agree that the wording is awkward and maybe implies the wrong thing. 

And thanks for the heads up and context on that - I don't think it will affect anything right now but that's definitely important to keep in mind going forward. I imagine as things evolve the content will need to be re-organized.  
___
*[`site/docs/concepts/bank/last-large-send.flow.yaml` line 11 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXAnF504SfkspiC6s:-N2s3tPm4XHnvMlXWi36:bmd97u2) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/last-large-send.flow.yaml#L11)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

optional nit: the `*.flow.ts` could just be `*.ts`.

`flow.ts` is vestigial from when we were looking for a ts module that lived alongside the flow catalog, also ending in `*.flow.yaml`, but isn't needed anymore and isn't a convention we want to push.

:shrug:  though.
</blockquote></details>

Updated throughout files
___
*[`site/docs/concepts/bank/.eslintrc.js` line 1 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qWlGRBYc-pzSRhpeH:-N2s3wdI1FMi0n0YKmfi:b-bi9ofp) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/.eslintrc.js#L1)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

You don't need to commit this file.
</blockquote></details>

my bad!
___
*[`site/docs/concepts/bank/.prettierrc.js` line 1 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qWs2o1cnLwMIQLnDJ:-N2s43t0DJnxmgTXK7wn:b-896fix) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/.prettierrc.js#L1)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

You don't need to commit this file
</blockquote></details>

Done.
___
*[`site/docs/concepts/bank/package.json` line 1 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXSK00YFl8bXtqa_4:-N2s44mW3w64RNel-DX2:b-896fix) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/package.json#L1)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

You don't need to commit this file
</blockquote></details>

Done.
___
*[`site/docs/concepts/bank/tsconfig.json` line 2 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXTVQ84zBLSZ_RWBg:-N2s45bxE2fF74yiV3IO:b-896fix) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/tsconfig.json#L2)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

You don't need to commit this file
</blockquote></details>

Done.
___
*[`site/docs/concepts/bank/flow_generated/tsconfig-files.json` line 3 at r5](https://reviewable.io/reviews/estuary/flow/473#-N2qXU6LCGlPxQbMzNxT:-N2s47Mj8tvNAxIE5Y3s:bd8fjql) ([raw file](https://github.com/estuary/flow/blob/a3174fbf45537a8185240e0d5fbde838140e9083/site/docs/concepts/bank/flow_generated/tsconfig-files.json#L3)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

You don't need to commit this file, or anything else under `flow_generated`.

I'll suggest adding a `.gitignore` file with `flow_generated` and other files which should be skipped.
</blockquote></details>

thanks - Will add to my workflow, wasn't thinking!

**Review by jgraettinger — APPROVED** [review]
LGTM! Thanks

**Review by jgraettinger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/estuary/flow/473)* status: 5 of 30 files reviewed, 9 unresolved discussions (waiting on @jgraettinger and @oliviamiannone)

___
*[`site/docs/concepts/flowctl.md` line 72 at r1](https://reviewable.io/reviews/estuary/flow/473#-N2qUEZL8K7N0xMtjjBg:-N2sDIS4B3L9NS1xVX2H:b3eui3m) ([raw file](https://github.com/estuary/flow/blob/eb21fab32b4681b0e789788a4f40204a932e0895/site/docs/concepts/flowctl.md#L72)):*
<details><summary><i>Previously, oliviamiannone wrote…</i></summary><blockquote>

Just referencing the difference between the generated TS files in flow_generated which the user never needs to touch, vs the ones that they have to manually configure to write lambdas. Seemed like a worthwhile distinction for someone poking around in a Flow catalog for the first time. Or at least, it was for my conceptual understanding. I do agree that the wording is awkward and maybe implies the wrong thing. 

And thanks for the heads up and context on that - I don't think it will affect anything right now but that's definitely important to keep in mind going forward. I imagine as things evolve the content will need to be re-organized.  
</blockquote></details>

This makes sense, I wasn't thinking sufficiently about `flow_generated` and how users might encounter / experience that.

**Pull request merged**
