### PR TITLE
Docs - managed DBs for MySql and Postgres; SSH

### PR DESCRIPTION
**Pull request by oliviamiannone**
**Description:**

Adds docs to...
- Mysql connector
- Postgres connector
- SSH setup guide 

...which covers implementations on...
- AWS
- GCloud 
- Azure

... per https://docs.google.com/document/d/18tLqjKmdVSyqGtTgXOdoHXrH_9OsqNumapmP5FVi3SE/edit.

**Notes for reviewers:**

Needs a second set of eyes for completeness and accuracy. It should be noted that while I did spend quite a bit of time reading and referencing the UI for the VMs and managed DBs on the three platforms, I didn't set up complete end-to-end dataflows for each workflow (for the sake of time, since complete testing was done quite recently).

Also looks like some of the changes to config tables I did recently got rolled into this PR (?). No need to review all that.

---
This change is [Reviewable](https://reviewable.io/reviews/estuary/flow/411)

### CODE REVIEW

**Review by dyaffe — COMMENTED** [review]
For AWS SSH server, step 1, I may just link to our SSH article when say "Find your public SSH key as created per this article", since it still has to be of that format and not just any will work.

Same with Step 1 for Google and Azure.

For adding SSH keys in Google, the easiest means is just to add them in the UI [here](https://console.cloud.google.com/compute/metadata?tab=sshkeys) vs via the api in the article mentioned in step 3.  I know that even Phil used that method.

One other related thing is that I notice you're referencing docs on creating these all via the CLI vs UI.  It probably makes sense for us to choose one and be consistent.  I would *think* that the UI would be simpler but it may be good to get an engineer to verify that.

**Comment by oliviamiannone** [comment]
@dyaffe thanks for the review!

> For AWS SSH server, step 1, I may just link to our SSH article when say "Find your public SSH key as created per this article", since it still has to be of that format and not just any will work.
> 
> Same with Step 1 for Google and Azure.

I'm a bit confused what you mean here. I think you're referring to the various sections of our SSH article, "Configure connections with SSH tunneling." I chose to break that article up into different set up steps for different use-cases: The generalized steps (what's live currently); and tailored steps for AWS, Google, and Azure. So, adding that link would just be linking to a different copy of the same step in the same article. 

I decided to set it up the way I did so that user only has to follow one set of steps and doesn't need to jump around the page. Some of the steps are duplicated for that reason -- so step 3 in the original workflow was copy-pasted into step 1 for the various managed platforms. It's just the ordering that changed. 

Let me know if I've misunderstood what you're trying to say, though. 

>For adding SSH keys in Google, the easiest means is just to add them in the UI [here](https://console.cloud.google.com/compute/metadata?tab=sshkeys) vs via the api in the article mentioned in step 3. I know that even Phil used that method.

I was digging into this and found this [article from Google](https://cloud.google.com/compute/docs/connect/add-ssh-keys). It's interesting because it says that to use the SSH keys for OS login, you have to use the CLI/API method. And when you use the UI (which is the Metadata configuration), they say that's for non-OS-login VMs. So would this mean that we _don't_ actually require OS login? 

> One other related thing is that I notice you're referencing docs on creating these all via the CLI vs UI. It probably makes sense for us to choose one and be consistent. I would think that the UI would be simpler but it may be good to get an engineer to verify that.

Good point - that should be consistent. I checked all the links. Amazon and Google are both pretty good about having instructions for both their consoles and CLI in the same docs, so we're good on all those links. Azure has _much_ more thorough docs on their CLI/API vs their Portal, but I was able to find stuff for the SSH docs. So now, the only CLI-only docs we link to should be in the Postgres connector docs for Azure. It's just one link, and I think that's find because the user will have to be running SQL commands for that, anyway.

**Comment by dyaffe** [comment]
For my first point, I was saying that in the article "Configure connections with SSH tunneling", in the first part of each section that talks about specific cloud providers you have a sentence that begins "Begin by finding your public SSH key on your local machine. In the .ssh".   My suggestion is that that sentence should be replaced with something like "Find or create your public SSH key as created per the General Setup portion of this article".  I agree with your chosen route of breaking the article up, but was just commenting on that one sentence.

re: your comment: "I was digging into this and found this [article from Google](https://cloud.google.com/compute/docs/connect/add-ssh-keys). It's interesting because it says that to use the SSH keys for OS login, you have to use the CLI/API method. And when you use the UI (which is the Metadata configuration), they say that's for non-OS-login VMs. So would this mean that we don't actually require OS login?"  -- @psFried Olivia seems to have a point.  Can you verify?

The rest looks good to me.

**Comment by oliviamiannone** [comment]
Going to go ahead and merge, even with that outstanding question about OS login and SSH keys in Google. Changed the link to the top of Google's article to leave it up to the user which method to use, and it's not like it's going to _hurt_ anything to use OS login even if it's not necessary. We can always adjust later.

**Pull request merged**
